### ISSUE TITLE
Add back in the option of using an external core

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig-vim#121]
This option was removed in #119.  Requested at https://github.com/editorconfig/editorconfig-vim/pull/119#issuecomment-498837689 .

@xuhdev Did a user request this feature?  Could you tell me a bit more about the use case?  I am confused.  Thanks!

**Comment by xuhdev** [comment]
Similar to https://github.com/editorconfig/editorconfig-emacs/pull/46#issuecomment-160042488 , the main reason is that external ones are written in more common languages that have a wider support. In case the user has the need, such as efficiency and enterprise customizability (they may customize one of the editorconfig CLI for instance). While setting the vimscript core as default makes the life of a lot of users much easier, I think it makes sense to retain the option to use an external EditorConfig CLI.

Ideally, I would say the option called something like `g:EditorConfig_external_command`. If it is empty (default), then the vimscript core is used. Otherwise the specified external command is used.

Does it make sense to you?

**Comment by cxw42** [comment]
@xuhdev I used `g:EditorConfig_exec_path`, since that is what it was before (see material removed in 37bedf88cabb61d4580295b6e347058df7e7f1b4).  I will submit a PR shortly.
