### ISSUE TITLE
Filename is wiped out when jumping to a buffer

### ISSUE THREAD

**Issue by scottperlitch** [editorconfig/editorconfig-vim#144]
Usually jumping to a buffer will immediately display the filename at the bottom of the screen. With editorconfig installed, the filename flashes and then disappears.

Commenting out Line 70 and 79 to prevent setting `&encoding`, fixes the issue but I'm wondering what consequences that has.
Using Vim 8.2 in Terminal/iTerm on MacOS 10.15

https://github.com/editorconfig/editorconfig-vim/blob/c5804257c6b38c5537b71ac91ed051c70eaeb5e5/autoload/editorconfig_core/ini.vim#L70-L79

**Comment by cxw42** [comment]
Thanks for reporting!  So the settings for the buffer are applied correctly, and the issue is only the display on the status line?

I also see the filename appear in the status line and then disappear almost immediately when I switch buffers.  I hadn't thought about it because I use [vim-airline](https://github.com/vim-airline/vim-airline), so I have the filename in the line above the status line.  Allow me to suggest airline or some other enhanced status line as a workaround :) .  [lightline](https://vimawesome.com/plugin/lightline-vim#introduction) looks like it might be another option.

**Comment by scottperlitch** [comment]
All settings seem to be applied correctly. Added a quick check to see if the encoding needs to be changed before changing it.
