### ISSUE TITLE
Unable to use command :E

### ISSUE THREAD

**Issue by HiImJulien** [editorconfig/editorconfig-vim#176]
Hey there!

I just installed this plugin manually; installed for VIM 8.2.2891.

The first thing I encountered that I cannot simply type ':E' to open the file explorer.
Sadly, I didn't find anything in the docs regarding this.

How can this be fixed?

**Comment by xuhdev** [comment]
Is `:E` from another plugin?

**Comment by HiImJulien** [comment]
No, it is the default `:E` as provided by Vim.

Currently I have no plugins BUT  your `editorconfig-vim`.

**Comment by HiImJulien** [comment]
Oh, I totally forgot to post the actual error I am encountering:
> Ambiguous use of user-defined command

**Comment by xuhdev** [comment]
What if you run `:Explore`?

**Comment by HiImJulien** [comment]
Running `:Explore` works.

**Comment by xuhdev** [comment]
I don't think `:E` is the shorthand for `:Explore` **only**. Before you installed EditorConfig, when you type `:E`, Vim detects `:Explore` because that's the only command starting with `E`. After installing EditorConfig, there are a few new commands starting with `:E` (e.g., `:EditorConfigDisable`), and therefore `:E` becomes ambiguous. If you try `:Ex`, `:Explore` should still be invoked. If you would like to keep using `:E`, you probably should add `command E :Explore` to your vimrc file.

Reference: `:h E183`

**Comment by HiImJulien** [comment]
I did not know that vim automatically matches commands.

Adding `command E :Explore` fixed this. Thanks!
