### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jirutka** [editorconfig/editorconfig-vim#228]
It’s over three years since the latest stable release and there are many new commits in the master. Can you please release (tag) a new version ASAP?

**Comment by cxw42** [comment]
Well, I think at least #224 needs to be resolved first (assistance welcome :) ).  Could you tell us more about your needs?  What is driving the request?

**Comment by jirutka** [comment]
I’m a maintainer of the [vim-editorconfig](https://pkgs.alpinelinux.org/packages?name=vim-editorconfig) package in Alpine Linux.

**Comment by cxw42** [comment]
Cool --- thanks for packaging this!  

@xuhdev I tagged v1.2.0 just before the merge (actually rebase) of #209.  I figure we can tag 1.2.1 once related issue #224 is resolved.

@jirutka In case you aren't aware, Vim 9.1 should already have the plugin (#223).

> some parts missing in v1.1.1

Which parts?  Just the [commits since then](https://github.com/editorconfig/editorconfig-vim/compare/v1.1.1...master), or are we missing a dependency or something?

**Comment by cxw42** [comment]
(Marking closed complete, but feel free to continue the discussion!)
