### ISSUE TITLE
Will this plugin become obsolete with Neovim v10?

### ISSUE THREAD

**Issue by fernandocanizo** [editorconfig/editorconfig-vim#234]
Hello, this is a question, not a bug.

Will `editorconfig-vim` become obsolete for users of Neovim now that version 10 will have EditorConfig recognition and application included?

**Comment by xuhdev** [comment]
I don't think you need to install this plugin for Neovim. However, this plugin is still useful for Vim and is not considered obsolete. After all, this is a "Vim" plugin :)

**Comment by scy** [comment]
Would it maybe make sense to add an overview in the readme that explains which versions of Vim and Neovim need this plugin and which don't? And also (if that's a thing) which EditorConfig features might be unavailable when using the built-in support versus when using the plugin?

**Comment by scy** [comment]
A version of this plugin (e014708e917b457e8f6c57f357d55dd3826880d4 from 2023-08-07) comes bundled with Vim since 9.0.1799, see https://github.com/vim/vim/pull/12902.

A Lua EditorConfig implementation comes bundled with Neovim since 0.9, see https://github.com/neovim/neovim/commit/ab9a2c49253413dbbb31756a3eeddb354a663035. It supports all properties [currently in the wiki](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties/af5b15a34ff8af21e8012e027112a0018e87423d), including `max_line_length`.

**Comment by xuhdev** [comment]
@scy Please check out https://github.com/editorconfig/editorconfig-vim/issues/223#issuecomment-1679561751 . While Vim now includes this plugin, the development still happens in this repo.

**Comment by scy** [comment]
@xuhdev Yes, I didn't disagree with that. My suggestion was to add a short section to the readme that explains to people who arrive at this repo whether they need to install it or whether their version of (Neo)Vim already comes with it.

**Comment by scy** [comment]
@xuhdev I've created #236 to show you what I mean.

**Comment by xuhdev** [comment]
Now clarified in README
