### ISSUE TITLE
optional graceful failure to load core

### ISSUE THREAD

**Issue by klaernie** [editorconfig/editorconfig-vim#62]
I have a single vim-config shared between many systems. Today I needed my global vim config for some specific features in the config, so I cloned my vim config, Vundle installed everything, but since then editorconfig-vim complains at each vim startup about the missing core.

To be clear: I do not intent to get the message itself removed, I would rather like a way to specify in my vimrc to ignore this failure after the first time showing it.

My preferred way would be a flag file, that editorconfig-vim will create, once it has shown the warning (maybe containing exactly the error that happened, so that different failure states can be ignored). The flag file location needs to be specified manually in the config, so a user like me can choose to ignore errors after seeing them once, but the regular user has no reason to specify the flagfile.

**Comment by xuhdev** [comment]
You can `let g:loaded_EditorConfig = 1` in your `.vimrc` to disable this plugin.... Is this what you need? I can add it to the doc.

**Comment by klaernie** [comment]
no, it would not solve the issue. It would stop editorconfig from working on all machines having my vim-config, if I check it in. If I don't I'll have to repeat the workaround again and again, and can't use the same config everywhere.

My main case is this: I have a shared home directory for a couple thousand servers (nfs-mounted). I have a couple of these servers where I do active development work, but many others where I just need to debug. If I skip loading editorconfig my dev-machines loose their feature-completeness, if I load it in my config I get annoyed in every debug-session.

My solution (presuming my idea would be implemented) would be specifying a flag file which name includes the current hostname (read from $HOSTNAME for example). That way on each host I get annoyed only once, and can determine if I want to fix the problem on this host, or leave it be.

**Comment by xuhdev** [comment]
How about this:

```
if executable('editorconfig')
    Initialize the plugin
endif
```

**Comment by kevinoid** [comment]
I'd like to see this feature as well.

The `if executable('editorconfig')` check suggested by @xuhdev isn't workable for me, since I don't have an `editorconfig` binary on most systems, but still use the Python implementation in this plugin when Python is available.  Although it would be possible to work out correct logic, it would require duplicating the behavior already in the plugin (to check for py2, py3, or editorconfig binary and skip if none), which seems fragile and needlessly duplicative.

I'd prefer a global variable to disable the load failure message.  Perhaps `g:EditorConfig_quiet` or allowing negative values for the existing `g:EditorConfig_verbose` to reduce verbosity below normal.  What do you think?  Is that something which might be accepted as a PR?

**Comment by cxw42** [comment]
The plugin now includes a core (#119).  Does that resolve this issue?

**Comment by klaernie** [comment]
That resolves the issue, thanks a lot!
